name: Merge Pull Request on Build Success

on:
  pull_request:
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        if: github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -B "${{ github.ref }}"
          git merge "${{ github.event.pull_request.head.sha }}"
          git push origin "${{ github.ref }}"
