name: Merge New Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          echo ${{ GITHUB_TOKEN }}
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git merge "${{ github.event.pull_request.head.sha }}"
          git push origin "${{ github.ref }}"
