name: Renovate

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run Renovate
        run: npx renovate
