name: Merge Renovate PR if Build Successful

on:
  push:
    branches:
      - renovate/*

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: |
          npm run build

      - name: Merge Renovate PR
        uses: repo-sync/pull-request@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          merge_method: 'squash'
          merge_commit_message: 'Merging Renovate PR'
          delete_branch: true
        if: ${{ success() }}
